# Generated by Django 5.2.3 on 2025-07-01 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_content', models.TextField()),
                ('encryption_key_hint', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('expiry_minutes', models.IntegerField(choices=[(5, '5 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '1 hour'), (360, '6 hours'), (1440, '24 hours'), (10080, '7 days')], default=60)),
                ('max_views', models.IntegerField(default=1)),
                ('current_views', models.IntegerField(default=0)),
                ('is_expired', models.BooleanField(default=False)),
                ('creator_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='notes.note')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
    ]
