# Generated by Django 5.2.3 on 2025-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteaccess',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
